### PR TITLE
fix(getstepdefinitionpaths.js): add shared level of steps (#590)

### LINKED ISSUE #590: Enhancement: Let multiple but not all feature files use the same step definitions
### Current behavior
Currently, when using non global step definitions you basically have two levels of step definitions:
- Per feature file: files in the folder with the same name as the feature file.
- Common: files in the `common`-folder (which can be customized).

### Desired behavior
Next to the above two levels of step definitions, also have a third, in-between level. This level can be used if you are already subdividing your feature files into multiple folders.

In a practical case: if you have an application with groups of features where each group is similar to each other, and you want to have the same step names used for each group but with different implementations, and you want to use multiple feature files within one group, then the current behavior won't suffice. Example setup:

```
/cypress
  /integration
    /common
      - a.ts
      - b.ts
      - ...
    /group1
      /feature-a
        - steps.ts
      /feature-b
        - steps.ts
      - feature-a.feature
      - feature-b.feature
      ...
    /group2
      /feature-a
        - steps.ts
      - feature-a.feature
      ...
```

Where each `feature-a.feature` contains similar tests, as the functionalities between the groups are similar. That results in each `feature-a.feature` using the same step names, but they need different implementations (as they are in different groups). This is possible if you do not have multiple feature files within one group, as for each group you would like to use the same step implementations, but then you would need to place them in `/common`, which would lead them to being used in different groups, which isn't compatible.

To summarize: having a third in-between level between steps per feature file and common steps, use a `shared` level where steps can be defined within the same folder as where the feature-files are (e.g. for `/group1/feature-a` and `/group1-feature-b` this would be `/group1/).

### Test code to reproduce
If necessary I can create a repository to show my implementation. I've tested it with my own setup and it works like a charm.

This issue seems similar as #475 and #231: 
- #475 has the same underlying problem, but they have determined to split up testing the groups over multiple repositories, leaving them without a folder for `common` steps over multiple repositories. We currently prefer having 1 feature file per group instead of not having any `common` steps over multiple groups.
- #231 contains basically the same request, but has a few requests in one issue, so I preferred creating a new one.

### PR DESCRIPTION
**Pull request by rdroog**
Fixes #590.

### CODE REVIEW

**Comment by rdroog** [comment]
If necessary I can change this from default behavior (which in theory might be backwards incompatible) to use config settings like:
- `sharedSteps` to enable/disable it.
- `sharedStepsFolder` to customize the folder (starting from the folder where the feature files are located with the default being that folder, but then you could also create a `shared` folder).

And/or make sure that the steps come from a `shared` folder within the folder of the feature files.

**Comment by rdroog** [comment]
@MateuszNowosad @lgandecki do you have any idea when you can look at my PR? Or is there any other method of getting my PR approved?

**Comment by lgandecki** [comment]
@rdroog this is a significant change that we would need to understand better. In the issue you mention this is an enhancement but here you made it as a fix - which suggests it fixes a bug. I might be mistaken here since I haven't read through the issue properly, just scrolled through - is this a fix or a feature?
Additionally, as @badeball mentions in #627 we should not be introducing changes without test coverage. I wouldn't ask anyone to do that for cypress-tags since there is no coverage there at all, but for the files that do have coverage it should be done

**Comment by badeball** [comment]
I think this MR is a mistake. It's an extension of an approach to configuration that is flawed in a way where it creates a lot of issue regarding "can't find my step definitions" and this wouldn't do anything to solve it. Instead, I think configuration should be re-thought and re-vamped. I did something different in my fork, which has worked well for us.

Here's some references

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/482#issuecomment-740474987
https://github.com/badeball/cypress-cucumber-preprocessor/pull/1
https://github.com/badeball/cypress-cucumber-preprocessor/commit/3292cf52f6747370b8ecd20ee274647e4a598d36

To explain, what I've done is that I've made so that eg.

```json
{
  "stepDefinitions": [
    "cypress/integration/[filepart].ts",
    "cypress/integration/[filepart]/step_definitions/**/*.ts"
  ]
}
```

.. would make eg. `cypress/integration/foo/bar/baz.feature` match all of the following files containing step definitions.

- cypress/integration/foo/bar/baz.ts
- cypress/integration/foo/bar/baz/step_definitions/steps.ts
- cypress/integration/foo/bar/step_definitions/steps.ts
- cypress/integration/foo/step_definitions/steps.ts
- cypress/integration/step_definitions/steps.ts

The way it works is that the feature-file's full path is resolved relatively to the integration folder and the extension removed, resulting in `foo/bar/baz`. This is split into `foo/bar/baz`, `foo/bar`, `foo` and `.`, which is used as replacements for `[filepart]`.

**Comment by badeball** [comment]
In case it's not clear, my suggested approach solves the issue this MR is trying to solve, along with a bunch of other scenarios people have described throughout issues.

Before any such significant change to configuration is made though, I think it would be wise to aggregate all issues and (currently) impossible scenarios described by other users into a post, in order to make sure that any proposed change solves a significant amount, while still retaining previous behavior / capabilities.

**Comment by rdroog** [comment]
@badeball: It seems and sounds like what you have implemented contains even more functionality (using shared steps on multiple different levels of the `filepart`). So it would definitely fit what we would need. Your proposed approach sounds reasonable. When creating #490 I already found the related issues #475 and #231, but there are probably more.

@lgandecki: Yes, it might be better suited as an enhancement. Would you prefer @badeball proposed solution too? In that case we can ignore this PR, and the other questions you've asked.

**Comment by badeball** [comment]
> Before any such significant change to configuration is made though, I think it would be wise to aggregate all issues and (currently) impossible scenarios described by other users into a post, in order to make sure that any proposed change solves a significant amount, while still retaining previous behavior / capabilities.

This is basically what a view as a requirement for anyone proposing changes to configuration now. I know this probably sucks to hear and suddenly contributing wasn't easy or even fun, but that's how it is when you're proposing changes affecting a huge number of other users. Unless anyone is willing to do that, then any MR related to this is likely to remain unreviewed, unfortunately.

**Comment by lgandecki** [comment]
@rdroog yeah I prefer @badeball solution, actually I agree with all the decisions he made in his fork, and we talked about joining forces, but I'm not so sure if we can skip the cucumber reporter, sounds like a ton of people are using that. It's also a huge source of issues and it made the code much more complex. 
As a temporary solution we could introduce some of the changes from the fork back here.

**Comment by badeball** [comment]
> but I'm not so sure if we can skip the cucumber reporter

I've previously been on the fence about this, but I want to try to make it work now. I just need to find some time to do it.

**Comment by merlosy** [comment]
I'm interested in having this feature as well. In the context of a monorepo, it would help a lot to share some generic step definitions across apps

**Comment by rdroog** [comment]
@merlosy: you can already have that with the `commonPath`, but that is just one level (so the shared generic step definitions would be used for either one `.feature`-file, or all). Both mine and badeball's proposed solution would add at least one more  level in between, so that you can have multiple levels or shared steps (e.g. having multiple `.feature`-files for one app and sharing some steps across all apps and some over just one app). Not sure if you only need the former, or also need the latter. My situation also contains is monorepo by the way.

@badeball / @lgandecki: is there any more information about the Cucumber reporter / is there a list of things still need to be done? I can't find it in the repo and I'd love to help out if possible.

**Comment by badeball** [comment]
I've found time lately to work on my fork and did manage implement support for JSON reporting, along with screenshot attachments and the `[filepart]` approach outlined above. You can check it out at https://github.com/badeball/cypress-cucumber-preprocessor.

**Comment by badeball** [comment]
@lgandecki, what are your thoughts about continuing to maintain the preprocessor?

Personally, I am intending to keep my fork. Furthermore, I can't see contributing to someone else's repository anymore, as I want to be able to chose my own tone in issues, etc.

**Comment by badeball** [comment]
Due to personal reasons, the previous maintainers of this package are stepping down and handing the reigns over to me, a long-time contributor to the project and a user of it myself. This is a responsibility I'm very excited about. Furthermore, I'd like to thank @lgandecki ++ for all the work that they've done so far.

Read more about the transfer of ownership [here](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689).

The repository has however moved and all outstanding issues are being closed. This is not a reflection of the perceived importance of your reported issue. However, if after upgrading to the new version, you still find there to be an issue, feel free to open up another ticket or comment below. Please make sure to read [CONTRIBUTING.md](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#instructions-for-logging-issues) before doing so.

**Pull request closed without merging**
