### PR TITLE
Bugfix/782

### PR DESCRIPTION
**Pull request by nilgaar**
fix for #782 

### Test:
**mytest.ts**
```
/// <reference types="cypress" />
import { DataTable, Given } from '@badeball/cypress-cucumber-preprocessor'

Given('I access the {string} webpage', (url: string) => {
    cy.visit(url)
})

Given('I print a table', (url: DataTable) => {})
```

**mytest.feature**
```
Feature: Printing

    I want to print all tables!

    @focus
    Scenario: Print with Cucumber
        Given I print a table
            | tal  | tal  |
            | tal1 | tal2 |
            | tal3 | tal4 |
            | tal5 | tal6 |

        Given I print a table
            | tal  | tal  | new  |
            | tal1 | tal2 | new2 |
            | tal3 | tal4 | new3 |
            | tal5 | tal6 | new4 |
```

Output:
image

### CODE REVIEW

**Comment by nilgaar** [comment]
the change is breaking a few tests, wip.

**Comment by badeball** [comment]
Can you see if you can use eg. `cli-table` to pretty format the table as well? Making this look appealing as well is a prerequisite for me FYI.

**Comment by RankaPalak** [comment]
@badeball / @nilgaar - just a question, will this be fixed for Javascript as well or just typescript?

**Comment by nilgaar** [comment]
@badeball The output is in a Markdown format, I'll check what's the best we can do with it.
@RankaPalak this will be fixed in the package, running in either JS or TS projects.

**Comment by hammzj** [comment]
@nilgaar I've used [as-table](https://github.com/xpl/as-table) in other projects and it prints out data tables correctly. Could that work here as well?

```js
const asTable = require('as-table');
const prettified = asTable.configure({delimiter: ' | '}) (dataTable.rawTable)
```

Edit: Nvm, this doesn't seem to work in the messages.

**Comment by nilgaar** [comment]
I think this is the best we can get @badeball , considering the limitations of the cy.console

**Comment by badeball** [comment]
Can you share what you have discovered regarding that limitation?

**Comment by nilgaar** [comment]
The main problem is that, for the `message` parameter, the 1st line is indentated differently from the others:
image

So, we have to assume this (because there's no way to make it fit perfectly with blank spaces) or either we skip the 1st line:
image

**Comment by hammzj** [comment]
Hey, wanna jump on this because I've been watching this conversation. As a second opinion, I like skipping the first line, but had some questions.

Can you show what happens based on the following data table transformations:
1. `dataTable.rawTable`
2. `dataTable.raw()` (rows without a header; traditionally I use this as `dataTable.raw().flat()` to use in steps)
3. `dataTable.rows()`
4. `dataTable.hashes()`
5. `dataTable.rowsHash()`
6. `dataTable.transpose()`
7. `docString` for steps that use a doc string instead of a dataTable
I'm referring [here for the different transformations](https://github.com/cucumber/cucumber-js/blob/main/src/models/data_table.ts). 

https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/data_table_interface.md

**Comment by nilgaar** [comment]
hi @hammzj. 
The current behavior of this PR is to print the table you pass to a step _raw_,  which means it is independent of which transformations you call over it afterwards.
By doing so, the output is printed only once; however, it also prints it in the same way regardless of whether the first line was intended to be a header...

**Comment by hammzj** [comment]
I totally must have missed that in my thought process. Will this work the same for a docString where it will print the text below the step?

**Comment by nilgaar** [comment]
It doesn't, but that's a cool idea for a follow-up PR 🕵🏻‍♂️

**Pull request merged**
